# Generated by Django 3.0.5 on 2020-04-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getflowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.CharField(default='1.jpeg', max_length=255),
            preserve_default=False,
        ),
    ]
