# Generated by Django 3.0.5 on 2020-04-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getflowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('R', 'Букеты из роз'), ('T', 'Тюльпаны'), ('B', 'Цветы в коробке'), ('F', 'Букеты цветов')], default='F', max_length=255),
        ),
    ]
